frontend/controllers/DashboardController.php
<?php

namespace frontend\controllers;

use common\models\User;
use frontend\models\About;
use frontend\models\Home;
use frontend\models\Img;
use Yii;
use frontend\models\Vendor;
use yii\db\Query;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\helpers\Url;

/**
 * DashboardController implements the CRUD actions for Vendor model.
 */
class DashboardController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'home', 'profile', 'gallery', 'about', 'file'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],

                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (in_array($action->id, ['file', 'view'])) {
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action);
    }

    public function actionIndex()
    {
        $this->view->title = 'Dashboard';
        $id = Yii::$app->user->id;
        $model = Vendor::findOne(['user_id' => $id]);
        $model->scenario = 'update';
        $model->email = Yii::$app->user->email;

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user = User::findOne($id);;
            $user->email = $model->email;
            if ($user->save() && $model->save()) {
                Yii::$app->session->setFlash('success', 'Profle updated successfully.');
                return $this->redirect(['profile', 'id' => $user->id]);
            } else {
                Yii::$app->session->setFlash('error', 'Somthing went wrong. Please try again later.');
            }
        }

        return $this->render('profile', [
            'model' => $model,
        ]);
    }

    public function actionHome()
    {
        $this->view->title = 'Home Page';
        $id = Yii::$app->user->id;
        $query = new Query();
        $query->select('i.home_header, i.home_slider1, i.home_slider2, i.gall_1, i.gall_2, i.gall_3, i.gall_4, h.short_about, h.working_hour')
            ->from('ks_img as i')
            ->join('LEFT JOIN', 'ks_home as h', "h.user_id = $id")
            ->where(['i.user_id' => $id]);
        $command = $query->createCommand();
        $a = $command->queryOne();

        if ($a) {
            $model = Home::find()->where(['user_id' => $id])->one();
            if (empty($model)) {
                $model = new Home();
            }
            $day = unserialize($a['working_hour']);
            $model->mon = @$day['mon'];
            $model->tue = @$day['tue'];
            $model->wed = @$day['wed'];
            $model->thu = @$day['thu'];
            $model->fri = @$day['fri'];
            $model->sat = @$day['sat'];
            $model->sun = @$day['sun'];
            $model->header = @$a['home_header'];
            $model->slider1 = @$a['home_slider1'];
            $model->gall1 = @$a['gall_1'];
            $model->gall2 = @$a['gall_2'];
            $model->gall3 = @$a['gall_3'];
            $model->gall4 = @$a['gall_4'];
        } else {
            $model = new Home();
        }
        $model->user_id = Yii::$app->user->id;
        if ($model->load(Yii::$app->request->post())) {
            $hour = array(
                'mon' => $_POST['Home']['mon'],
                'tue' => $_POST['Home']['tue'],
                'wed' => $_POST['Home']['wed'],
                'thu' => $_POST['Home']['thu'],
                'fri' => $_POST['Home']['fri'],
                'sat' => $_POST['Home']['sat'],
                'sun' => $_POST['Home']['sun'],
            );
            $model->working_hour = serialize($hour);
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Saved successfully');
                return $this->redirect(['home']);
            } else {
                Yii::$app->session->setFlash('error', "Change few things and try again or contact admin.");
            }
        }

        return $this->render('home', [
            'model' => $model,
        ]);
    }

    public function actionAbout()
    {
        $this->view->title = 'About Page';
        $id = Yii::$app->user->id;
        $query = new Query();
        $query->select('i.home_header, i.about_img')
            ->from('ks_img as i')
            ->join('LEFT JOIN', 'ks_about as a', "a.user_id = $id")
            ->where(['i.user_id' => $id]);
        $command = $query->createCommand();
        $a = $command->queryOne();

        if ($a) {
            $model = About::find()->where(['user_id' => $id])->one();
            if (empty($model)) {
                $model = new About();
            }
            $model->header = @$a['home_header'];
            $model->about_img = @$a['about_img'];
        } else {
            $model = new About();
        }
        $model->user_id = Yii::$app->user->id;
        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Saved successfully');
                return $this->redirect(['about']);
            } else {
                Yii::$app->session->setFlash('error', "Change few things and try again or contact admin.");
            }
        }
        return $this->render('about', [
            'model' => $model
        ]);
    }

    public function actionGallery()
    {
        $this->view->title = 'Gallery';
        $model = Img::find()->where(['user_id' => Yii::$app->user->id])->one();
        if (empty($model)) {
            $model = new Img();
        }

        return $this->render('gallery', [
            'model' => $model
        ]);
    }

    public function actionContact()
    {
        $this->view->title = 'Contact';
        $id = Yii::$app->user->id;
        $query = new Query();
        $query->select('i.home_header')
            ->from('ks_img as i')
            ->join('LEFT JOIN', 'ks_about as a', "a.user_id = $id")
            ->where(['i.user_id' => $id]);
        $command = $query->createCommand();
        $a = $command->queryOne();
        $model = Vendor::find()->where(['user_id' => $id])->one();
        $model->home_header = @$a['home_header'];
        $model->user_id = $id;
        $model->email = Yii::$app->user->email;
        return $this->render('contact', [
            'model' => $model
        ]);
    }

    public function actionFile()
    {
        if (Yii::$app->request->isAjax) {
            if ($_FILES['img']['name']) {
                $uploadedFile = '';
                if (!empty($_FILES["img"]["type"])) {
                    $valid_extensions = array("jpeg", 'png', 'jpg'); //validation
                    $temporary = explode(".", $_FILES["img"]["name"]);
                    $file_extension = end($temporary);
                    $fileName = $this->generateRandomString() . time() . '.' . $file_extension; //random file name

                    if (($_FILES["img"]["type"] == ("image/jpeg" || "image/png" || "image/JPEG" || "image/PNG")) && in_array($file_extension, $valid_extensions)) //check file extension
                    {
                        $sourcePath = $_FILES['img']['tmp_name'];
                        $path = Yii::getAlias('@webroot') . '/theme/user/' . yii::$app->user->name;
                        if (!file_exists($path)) //folder exsist or not if not then add
                        {
                            mkdir($path, 0755, true);
                        }

                        $targetPath = $path . '/' . $fileName;
                        if (move_uploaded_file($sourcePath, $targetPath)) {
                            $uploadedFile = $fileName;
                            /* 
                            * logo upload
                            */
                            if ($_POST['type'] == '#logo') {
                                $logo = Vendor::find()->where(['user_id' => yii::$app->user->id])->one();
                                @unlink($path . '/' . $logo->image);
                                $logo->image = $uploadedFile;
                                $logo->save(false);

                                $data['msg'] = 'success';
                                $data['status'] = 'Image updated.';
                                $data['image'] = Url::Home(true) . "theme/user/" . Yii::$app->user->name . "/" . $uploadedFile;
                                echo json_encode($data);
                                yii::$app->end();
                            } else {
                                $model = Img::find()->where(['user_id' => yii::$app->user->id])->one();
                                if (empty($model)) {
                                    $model = new img();
                                } else {
                                    ($_POST['type'] == '#home_header') ? @unlink($path . '/' . $model->home_header) : '';
                                    ($_POST['type'] == '#slider1') ? @unlink($path . '/' . $model->home_slider1) : '';
                                    ($_POST['type'] == '#slider2') ? @unlink($path . '/' . $model->home_slider2) : '';
                                    ($_POST['type'] == '#gall1') ? @unlink($path . '/' . $model->gall_1) : '';
                                    ($_POST['type'] == '#gall2') ? @unlink($path . '/' . $model->gall_2) : '';
                                    ($_POST['type'] == '#gall3') ? @unlink($path . '/' . $model->gall_3) : '';
                                    ($_POST['type'] == '#gall4') ? @unlink($path . '/' . $model->gall_4) : '';
                                    ($_POST['type'] == '#gall5') ? @unlink($path . '/' . $model->gall_5) : '';
                                    ($_POST['type'] == '#gall6') ? @unlink($path . '/' . $model->gall_6) : '';

frontend/views/layouts/dashboard.php
<?php

use yii\widgets\Menu;
use yii\helpers\Url;

$logo  = URL::Home(true) . "theme/images/avatar/4.jpg";
if (Yii::$app->user->logo) {
    $logo = URL::Home(true) . "theme/user/" . Yii::$app->user->name . "/" . Yii::$app->user->logo;
}
?>
<link type="text/css" rel="stylesheet" href="<?= Url::home(true); ?>theme/css/dashboard-style.css">

<!--  section  -->
<section class=" parallax-section dashboard-header-sec gradient-bg" data-scrollax-parent="true">
    <div class="container">
        <div class="dashboard-breadcrumbs breadcrumbs"><a href="#">Home</a><a href="#">Dashboard</a><span>Main page</span></div>
        <!--Tariff Plan menu-->
        <div class="tfp-btn"><span>Tariff Plan : </span> <strong>Extended</strong></div>
        <div class="tfp-det">
            <p>You Are on <a href="#">Extended</a> . Use link bellow to view details or upgrade. </p>
            <a href="#" class="tfp-det-btn color2-bg">Details</a>
        </div>
        <!--Tariff Plan menu end-->
        <div class="dashboard-header_conatiner fl-wrap dashboard-header_title">
            <h1>Welcome : <span><?= ucfirst(Yii::$app->user->name) ?></span></h1>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="dashboard-header fl-wrap">
        <div class="container">
            <div class="dashboard-header_conatiner fl-wrap">
                <div class="dashboard-header-avatar">

                    <img src="<?= $logo ?>" alt="">
                    <a href="javascript:void(0)" class="color-bg edit-prof_btn" data-tag="logo"><i class="fal fa-edit"></i></a>
                    <input id="logo" type="file" name="logo" style="display: none;" onchange="test()" />
                </div>
                <div class="dashboard-header-stats-wrap">
                    <div class="dashboard-header-stats">
                        <div class="swiper-container">
                            <div class="swiper-wrapper">
                                <!--  dashboard-header-stats-item -->
                                <div class="swiper-slide">
                                    <div class="dashboard-header-stats-item">
                                        <i class="fal fa-map-marked"></i>
                                        Active Listings
                                        <span>21</span>
                                    </div>
                                </div>
                                <!--  dashboard-header-stats-item end -->
                                <!--  dashboard-header-stats-item -->
                                <div class="swiper-slide">
                                    <div class="dashboard-header-stats-item">
                                        <i class="fal fa-chart-bar"></i>
                                        Listing Views
                                        <span>1054</span>
                                    </div>
                                </div>
                                <!--  dashboard-header-stats-item end -->
                                <!--  dashboard-header-stats-item -->
                                <div class="swiper-slide">
                                    <div class="dashboard-header-stats-item">
                                        <i class="fal fa-comments-alt"></i>
                                        Total Reviews
                                        <span>79</span>
                                    </div>
                                </div>
                                <!--  dashboard-header-stats-item end -->
                                <!--  dashboard-header-stats-item -->
                                <div class="swiper-slide">
                                    <div class="dashboard-header-stats-item">
                                        <i class="fal fa-heart"></i>
                                        Times Bookmarked
                                        <span>654</span>
                                    </div>
                                </div>
                                <!--  dashboard-header-stats-item end -->
                            </div>
                        </div>
                    </div>
                    <!--  dashboard-header-stats  end -->
                    <div class="dhs-controls">
                        <div class="dhs dhs-prev"><i class="fal fa-angle-left"></i></div>
                        <div class="dhs dhs-next"><i class="fal fa-angle-right"></i></div>
                    </div>
                </div>
                <!--  dashboard-header-stats-wrap end -->
                <a class="add_new-dashboard">Add Listing <i class="fal fa-eye"></i></a>
            </div>
        </div>
    </div>
    <div class="gradient-bg-figure" style="right:-30px;top:10px;"></div>
    <div class="gradient-bg-figure" style="left:-20px;bottom:30px;"></div>
    <div class="circle-wrap" style="left:120px;bottom:120px;" data-scrollax="properties: { translateY: '-200px' }">
        <div class="circle_bg-bal circle_bg-bal_small"></div>
    </div>
    <div class="circle-wrap" style="right:420px;bottom:-70px;" data-scrollax="properties: { translateY: '150px' }">
        <div class="circle_bg-bal circle_bg-bal_big"></div>
    </div>
    <div class="circle-wrap" style="left:420px;top:-70px;" data-scrollax="properties: { translateY: '100px' }">
        <div class="circle_bg-bal circle_bg-bal_big"></div>
    </div>
    <div class="circle-wrap" style="left:40%;bottom:-70px;">
        <div class="circle_bg-bal circle_bg-bal_middle"></div>
    </div>
    <div class="circle-wrap" style="right:40%;top:-10px;">
        <div class="circle_bg-bal circle_bg-bal_versmall" data-scrollax="properties: { translateY: '-350px' }"></div>
    </div>
    <div class="circle-wrap" style="right:55%;top:90px;">
        <div class="circle_bg-bal circle_bg-bal_versmall" data-scrollax="properties: { translateY: '-350px' }"></div>
    </div>
</section>

<!--  section  end-->
<section class="gray-bg main-dashboard-sec" id="sec1">
    <div class="container">
        <!--  dashboard-menu-->
        <div class="col-md-3">
            <div class="mob-nav-content-btn color2-bg init-dsmen fl-wrap"><i class="fal fa-bars"></i> Dashboard menu</div>
            <div class="clearfix"></div>
            <div class="fixed-bar fl-wrap" id="dash_menu">
                <div class="user-profile-menu-wrap fl-wrap block_box">
                    <!-- user-profile-menu-->
                    <div class="user-profile-menu">
                        <h3>Main</h3>
                        <?php
                        echo Menu::widget([
                            'items' => [
                                ['label' => '<i class="fal fa-chart-line"></i>Dashboard', 'url' => ['//dashboard/index']],
                                ['label' => '<i class="fal fa-home"></i>Home Page', 'url' => ['//dashboard/home']],
                                ['label' => '<i class="fal fa-file-alt"></i>About Page', 'url' => ['//dashboard/about']],
                                ['label' => '<i class="fal fa-images"></i>Gallery', 'url' => ['//dashboard/gallery']],
                                ['label' => '<i class="fal fa-id-card"></i>Contact', 'url' => ['//dashboard/contact']],
                            ],
                            'activateParents' => true,
                            'encodeLabels' => false,
                            'activeCssClass' => 'user-profile-act',
                            'options' => [
                                'class' => 'no-list-style',
                            ],
                        ]);
                        ?>
                    </div>
                    <a class="logout_btn color2-bg" href="<?= Url::to(['site/logout']) ?>">Log Out <i class="fas fa-sign-out"></i></a>
                </div>
            </div>
            <a class="back-tofilters color2-bg custom-scroll-link fl-wrap" href="#dash_menu">Back to Menu<i class="fas fa-caret-up"></i></a>
        </div>
        <!-- dashboard-menu  end-->
        <!-- dashboard content-->
        <div class="col-md-9">
            <?= $content ?>
        </div>
</section>
<!--  section  end-->
<div class="limit-box fl-wrap"></div>

<script src="<?= Url::home(true); ?>theme/js/charts.js"></script>
<script src="<?= Url::home(true); ?>theme/js/dashboard.js"></script>
<script>
    var id;
    $('a').on('click', function() {
        id = '#' + $(this).attr('data-tag');
        $(id).trigger('click');
    });

    function test() {
        var file = $(id).prop('files')[0];
        var imagefile = file.type;
        var match = ["image/jpeg", "image/png", "image/JPEG", "image/PNG"];
        if (!((imagefile == match[0]) || (imagefile == match[1]) || (imagefile == match[2]))) {
            swt("error", 'Uploaded file is not image.');
            $(id).val('');
            return false;
        } else {
            submit(id);
        }
    }

    //header image
    function homeHeader(obj) {
        $('#temp_i').hide();
        $('#final_i').show();
        $('.par-elem').attr('data-bg', obj.image);
        $('.parth').css({
            'background-image': 'url("' + obj.image + '")'
        });
    }

    //slider1 image
    function slider(obj) {
        $('.respimg').attr('src', obj.image);
    }

    //gall image
    function gall(obj, id) {
        $(id).closest('div').find('img').attr('src', obj.image);
        $(id).closest('div').find('a').attr('href', obj.image);
    }

    function about_img(obj, id) {
        $(id).closest('div').find('img').attr('src', obj.image);
    }

    function logo(obj, id) {
        $(id).closest('div').find('img').attr('src', obj.image);
    }

    //image upload
    function submit(id) {
        var file_data = $(id).prop('files')[0];
        var formData = new FormData();
        formData.append('img', file_data);
        formData.append('type', id);
        $.ajax({
            type: 'POST',
            url: '<?= \Yii::$app->urlManager->createAbsoluteUrl(["/dashboard/file"]) ?>',
            data: formData,
            cache: false,
            contentType: false,
            processData: false,
            success: function(data) {
                var obj = jQuery.parseJSON(data);
                if (obj.msg == 'success') {
                    var msg = obj.msg.toUpperCase();
                    (id == '#home_header') ? homeHeader(obj): '';
                    (id == '#slider1') ? slider(obj): '';
                    (id == '#gall1') ? gall(obj, id): '';
                    (id == '#gall2') ? gall(obj, id): '';
                    (id == '#gall3') ? gall(obj, id): '';
                    (id == '#gall4') ? gall(obj, id): '';
                    (id == '#gall5') ? gall(obj, id): '';
                    (id == '#gall6') ? gall(obj, id): '';
                    (id == '#gall7') ? gall(obj, id): '';
                    (id == '#gall8') ? gall(obj, id): '';
                    (id == '#logo') ? logo(obj, id): '';
                    (id == '#about_img') ? about_img(obj, id): '';
                    $(id).val('');
                    swt(obj.msg, obj.status);
                } else {
                    $(id).val('');
                    swt(obj.msg, obj.status);
                }
            }
        });
    };

    CKEDITOR.instances.editor.on('change', function() {
        textSave('home');
    });

    function textSave(page) {
        $('.to-top-custom').show();
    }

    //texarea
    $().on
</script>

frontend/views/layouts/user-main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use common\widgets\Alert;
use yii\helpers\Url;

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">

<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <meta name="robots" content="index, follow" />
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <!--=============== css  ===============-->
    <link type="text/css" rel="stylesheet" href="<?= Url::home(true); ?>theme/css/reset.css">
    <link type="text/css" rel="stylesheet" href="<?= Url::home(true); ?>theme/css/plugins.css">
    <link type="text/css" rel="stylesheet" href="<?= Url::home(true); ?>theme/css/user.css">

    <link type="text/css" rel="stylesheet" href="<?= Url::home(true); ?>theme/css/color.css">
    <!--=============== favicons ===============-->
    <link rel="shortcut icon" href="<?= Url::home(true); ?>theme/images/favicon.ico">
    <script src="<?= Url::home(true); ?>theme/js/jquery.min.js"></script>
    <style>
        .error-cust {
            color: #e83e4e;
            text-align: left;
            font-size: 11px;
            padding-bottom: 5px;
        }

        .has-success>input {
            border-color: #10b759 !important;
        }

        .has-error>input {
            border-color: #e83e4e !important;
        }

        .is-invalid>input {
            border-color: #e83e4e;
        }

        .is-invalid>select {
            border-color: #e83e4e;
        }

        .required label:after {
            content: " *";
        }

        .col-sm-6.field-vendor-url {
            text-align: left !important;
        }

        #vendor-url {
            margin-bottom: 5px;
        }

        .sml {
            font-size: 12px;
            color: #878C9F;
        }

        .absolute-wrap {
            margin-top: 0px;
            background: none;
            border-radius: 0px;
            box-shadow: none;
        }

        .edit-prof_btn_right {
            position: absolute;
            bottom: 6px;
            right: 0px;
            width: 36px;
            height: 36px;
            line-height: 36px;
            border-radius: 100%;
            color: #fff;
            z-index: 4;
            text-align: center;
            box-shadow: 0 9px 26px rgba(58, 87, 135, 0.2);
        }

        .header-logo {
            position: absolute;
            left: -10px;
            height: 100px;
            width: 100px;
            border-radius: 100%;
        }

        .header-logo:before {
            content: '';
            position: absolute;
            left: -5px;
            top: -5px;
            right: -5px;
            bottom: -5px;
            background: #fff;
            z-index: 1;
            border-radius: 100%;
        }

        .header-logo img {
            height: 100px !important;
            width: 100px;
            border-radius: 100%;
            position: relative;
            z-index: 3;
        }
    </style>
    <?php $this->head() ?>
</head>

<body>
    <?php $this->beginBody() ?>

    <!--loader-->
    <div class="loader-wrap">
        <div class="loader-inner">
            <div class="loader-inner-cirle"></div>
        </div>
    </div>
    <!--loader end-->
    <!-- main start  -->
    <div id="main">
        <!-- content-->
        <div class="content">
            <?= $content; ?>
        </div>

        <!-- wrapper end-->
        <!--footer -->
        <footer class="main-footer fl-wrap">
            <!-- footer-header-->
            <div class="footer-header fl-wrap grad ient-dark">
                <div class="container">
                    <div class="row">
                        <div class="col-md-5">
                            <div class="subscribe-header">
                                <h3>Subscribe For a <span>Newsletter</span></h3>
                                <p>Whant to be notified about new locations ? Just sign up.</p>
                            </div>
                        </div>
                        <div class="col-md-7">
                            <div class="subscribe-widget">
                                <div class="subcribe-form">
                                    <form id="subscribe">
                                        <input class="enteremail fl-wrap" name="email" id="subscribe-email" placeholder="Enter Your Email" spellcheck="false" type="text">
                                        <button type="submit" id="subscribe-button" class="subscribe-button"><i class="fal fa-envelope"></i></button>
                                        <label for="subscribe-email" class="subscribe-message"></label>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- footer-header end-->

            <!--sub-footer-->
            <div class="sub-footer  fl-wrap">
                <div class="container">
                    <div class="copyright"> &copy; <?= Html::encode(Yii::$app->name) ?> <?= date('Y') ?>. All rights reserved.</div>
                    <div class="lang-wrap">
                        <div class="show-lang"><span><i class="fal fa-globe-europe"></i><strong>En</strong></span><i class="fa fa-caret-down arrlan"></i></div>

                    </div>
                    <div class="subfooter-nav">
                        <ul class="no-list-style">
                            <li><a href="#">Terms of use</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Blog</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!--sub-footer end -->
        </footer>
        <!--footer end -->
        <!--map-modal -->
        <div class="map-modal-wrap">
            <div class="map-modal-wrap-overlay"></div>
            <div class="map-modal-item">
                <div class="map-modal-container fl-wrap">
                    <div class="map-modal fl-wrap">
                        <div id="singleMap" data-latitude="40.7" data-longitude="-73.1"></div>
                    </div>
                    <h3><span>Location for : </span><a href="#">Listing Title</a></h3>
                    <div class="map-modal-close"><i class="fal fa-times"></i></div>
                </div>
            </div>
        </div>
        <!--map-modal end -->

        <a class="to-top"><i class="fas fa-caret-up"></i></a>
    </div>

    <?php $this->endBody() ?>
    <!-- Main end -->
    <!--=============== scripts  ===============-->

    <script src="<?= Url::home(true); ?>theme/js/plugins.js"></script>
    <script src="<?= Url::home(true); ?>theme/js/scripts2.js"></script>
    <script src="<?= Url::home(true); ?>theme/js/map-single.js"></script>
    <script src="<?= Url::home(true); ?>theme/js/sweetalert.js"></script>
    <script>
        <?php
        if (Yii::$app->session->hasFlash('success')) {
            $msg = (empty(Yii::$app->session->getFlash("success"))) ? '' : Yii::$app->session->getFlash("success");
            echo '$( document ).ready(function() { swt( "success", "' . $msg . '") });';
        } elseif (Yii::$app->session->hasFlash('error')) {
            echo '$( document ).ready(function() { swt( "error", "' . Yii::$app->session->getFlash('error') . '") });';
        }
        ?>

        function custerror(from, data, input) {
            $.each(data, function(index, element) {
                $(from).yiiActiveForm('updateAttribute', index, element);
            });
        }

        // alert msg
        function swt(type, msg) {
            const Toast = Swal.mixin({
                toast: true,
                position: 'top-end',
                showConfirmButton: false,
                timer: 5000,
                timerProgressBar: true,
                onOpen: (toast) => {
                    toast.addEventListener('mouseenter', Swal.stopTimer)
                    toast.addEventListener('mouseleave', Swal.resumeTimer)
                }
            })

            Toast.fire({
                icon: type,
                title: msg
            })
        }
    </script>
</body>

</html>
<?php $this->endPage() ?>